In [1]:
import pandas as pd

## Abrindo o primeiro arquivo de dados

In [3]:
df = pd.read_csv('dados.csv')
df

        Indice  Cidade  Genero  Idade     Renda Enfermidade
0            1  Dallas    Male     41   40367.0          No
1            2  Dallas    Male     54   45084.0          No
2            3  Dallas    Male     42   52483.0          No
3            4  Dallas    Male     40   40941.0          No
4            5  Dallas    Male     46   50289.0          No
...        ...     ...     ...    ...       ...         ...
149995  149996  Austin    Male     48   93669.0          No
149996  149997  Austin    Male     25   96748.0          No
149997  149998  Austin    Male     26  111885.0          No
149998  149999  Austin    Male     25  111878.0          No
149999  150000  Austin  Female     37   87251.0          No

[150000 rows x 6 columns]